CMakeLists.txt
See https://github.com/dbarrow257/ProbGPU/pull/1 for details
=> Cuda Architecture

CMakeLists.txt, Oscillator/CMakeLists.txt
Tested with 
`cmake ../ -DUseGPU=0 -DUseMultithreading=1 -DUseDoubles=0 -DUseCUDAProb3=0 -DUseCUDAProb3Linear=1 -DUseProb3ppLinear=0 -DUseProbGPULinear=0`
=> Fix weird cmake problems

OscProbCalcer/CMakeLists.txt, OscProbCalcer/OscProbCalcerFactory.cpp, OscProbCalcer/OscProbCalcerFactory.h, Oscillator/OscillatorBase.cpp
Add factory class to create instances of OscProbCalcerBase objects
Moved creation of OscProbCalcerBase in OscillatorBase object to it's own class so it can be called anywhere
=> Add factory class to create instances of OscProbCalcerBase objects

Apps/SingleOscProbCalcer.cpp, Constants/OscillatorConstants.h, OscProbCalcer/OscProbCalcerBase.cpp, OscProbCalcer/OscProbCalcerBase.h, OscProbCalcer/OscProbCalcerFactory.cpp, OscProbCalcer/OscProbCalcer_CUDAProb3.cpp, OscProbCalcer/OscProbCalcer_CUDAProb3Linear.cpp, Oscillator/OscillatorBase.cpp, Oscillator/OscillatorBinned.cpp
Address https://github.com/dbarrow257/NuOscillator/issues/38 by protecting enums behind a namespace
Also use OscProbCalcerFactory method in Apps/SingleOscProbCalcer exec
All enums defined within the constants are now protected behind a NuOscillator:: namespace
=> Feature namespace

.github/workflows/Linter.yml, Docs/DockerFiles/Rocky9/Dockerfile, README.md
- Linter for yaml and markdown
- updates documentation etc
=> tidy: Update documentation

Configs/OscProbCalcerConfigs/OscProb.yaml, OscProbCalcer/OscProbCalcer_OscProb.cpp, OscProbCalcer/OscProbCalcer_OscProb.h
Update on OscProb implementation in NuOscillator
Addition of possibility to handle Scalar Non Standard Interaction and Lorentz Invariance Violation models
Earth model file path now to be given in the config file
Detector depth now taken into account and to be given in config file
[Update OscProb implementation in NuOscillator Pull Request.pdf](https://github.com/user-attachments/files/18380128/Update.OscProb.implementation.in.NuOscillator.Pull.Request.pdf)
=> Feature osc prob update

CMakeLists.txt
=> Bump to version 1.1.0

.github/workflows/CDImage.yml, Docs/DockerFiles/Alma9/Dockerfile
Change name of docker image so it is used consisntenly when making relase
=> Minor fixes

Apps/Analysis.cpp, Apps/DragRace.cpp, Apps/OscProbCalcerComparison.cpp, Apps/SingleOscProbCalcer.cpp, Apps/SingleOscillator.cpp, Constants/OscillatorConstants.h, OscProbCalcer/OscProbCalcerBase.cpp, OscProbCalcer/OscProbCalcerFactory.cpp, OscProbCalcer/OscProbCalcer_CUDAProb3.cpp, OscProbCalcer/OscProbCalcer_CUDAProb3Linear.cpp, OscProbCalcer/OscProbCalcer_NuFASTLinear.cpp, OscProbCalcer/OscProbCalcer_OscProb.cpp, Oscillator/OscillatorBase.cpp, Oscillator/OscillatorBinned.cpp, Oscillator/OscillatorFactory.cpp
Throw runtime errors which can be caught be any external library which uses NuOscillator
=> Throw runtime errors rather than no exception

CMakeLists.txt
=> Bump OscProb to v2.1.2

.github/workflows/CIValidations.yml, Apps/DragRace.cpp, Configs/Binned_CUDAProb3.yaml, Configs/Binned_OscProb.yaml, Configs/OscProbCalcerConfigs/CUDAProb3.yaml, Configs/OscProbCalcerConfigs/OscProb.yaml, Configs/Unbinned_CUDAProb3.yaml, Configs/Unbinned_OscProb.yaml, Constants/OscillatorConstants.h, Docs/Notes
Some of the configs were not usable as additional options were required by engines and hadn't been added to all configs
Additionally, adding the number of iterations used in the DragRace app as an argument
=> BugFix: Cleanup configs

CMakeLists.txt
Bump version to incorporate all recent changes
=> Bump to v1.1.2

CMakeLists.txt, README.md
Include intended extensions into README and bump version
=> Doc: README update

.github/workflows/Benchmark.yml, README.md
This bot will udpate bencahrmiking plot in readem.
Original plot is stored in https://github.com/dbarrow257/NuOscillator/tree/gh-plots
Bot simply after PR is merged will update it. Readme refers to plot in that branch
=> Benchamrk Bot Plot

OscProbCalcer/OscProbCalcer_NuSQUIDSLinear.cpp, OscProbCalcer/OscProbCalcer_NuSQUIDSLinear.h
Instead of defining pointer of every model, just use same pinter but use casting.
In case there are more models should make easier to follow what is being used.
=> Proper Casting for NuSQIUD

OscProbCalcer/OscProbCalcer_NuFASTLinear.cpp, OscProbCalcer/OscProbCalcer_NuFASTLinear.h
Also allow N_Newtons to be config settable
=> feat: Remove probability sanity checking in NuFAST

CMakeLists.txt, Setup.sh
=> feat: Try finding hdf5 both with and without the components keyword

Apps/DragRace.cpp, Apps/OscProbCalcerComparison.cpp, Apps/SingleOscProbCalcer.cpp, Apps/SingleOscillator.cpp, CMakeLists.txt, Constants/OscillatorConstants.h
argv[0] give executable name, no need to hardcdoe it.
Also return Osc params were missing doxygen docuemantion.
And some other minor tidy
=> Tidy Documentation and Usage()

OscProbCalcer/OscProbCalcer_CUDAProb3.cpp
This allows chemical compositions to be fed into CUDAProb3 as extra oscillation parameters. This technically could have been implemented with weights, but will be easier for clarity's sake as separate parameters.
=> Added chemical composition argument inputs for CUDAProb3

.github/workflows/Benchmark.yml, NuOscillatorConfigs/SubSampling_CUDAProb3.yaml, OscProbCalcer/OscProbCalcer_CUDAProb3.cpp, Oscillator/OscillatorSubSampling.cpp, README.md
Now check for zero division is before actual division
Subsamiling now is showed in benchamriking readme
=> feat: Include sub sampling benchamriking

CMakeLists.txt
=> feat: Allow particular commit/branch/tag of engine to be pulled via CMake envokation

CMakeLists.txt
=> feat: Update CMakeLists.txt to bump ProbGPU

CMakeLists.txt
=> Bump version to 1.3.1

.github/workflows/WeeklyValgrind.yml, Apps/DragRace.cpp
Have weekly bot which make check memory leaks and genral RAM usage via massif
Files are storred here: https://github.com/dbarrow257/NuOscillator/tree/gh-profiling
https://github.com/dbarrow257/NuOscillator/actions/runs/14928042229/job/41937262765?pr=125
=> feat: Weekl Valgrind Bot

Doxyfile
- Properly include Main page
- Add depdancy graph for classes
- Bump version
=> Udpate Doxyfile

CMakeLists.txt
Use Tagged Version of CudaProb3 and Prob3++
=> CudaProb3 and Prob3++ Tag

Apps/OscProbCalcerComparison.cpp, Constants/OscillatorConstants.h, NuOscillatorConfigs/Binned_NuSQUIDSLinear.yaml, NuOscillatorConfigs/Unbinned_NuSQUIDSLinear.yaml, OscProbCalcer/OscProbCalcer_NuSQUIDSLinear.cpp
=> feat: Modification to NuSQUIDS IInteraction and associated apps

CMakeLists.txt
=> feat: Bump CUDAProb3 version to include Radius fix on GPU

CMakeLists.txt, OscProbCalcer/OscProbCalcer_CUDAProb3Linear.cpp, OscProbCalcer/OscProbCalcer_CUDAProb3Linear.h
=> feat: Allow for renamed namespace in CUDAProb3Linear

.github/workflows/CDImage.yml, .github/workflows/CIBuild.yml
Make sure CudaProbATM and CudaProbBeam are compiled at the same time within CI/CD also NuSquid was missing
=> feat: More bots
