dbarrow257/NuOscillator

- .gitignore
- Apps/DragRace.cpp
- Apps/OscProbCalcerComparison.cpp
- CMakeLists.txt
- OscProbCalcer/OscProbCalcerBase.cpp
- OscProbCalcer/OscProbCalcerBase.h
- OscProbCalcer/OscProbCalcer_CUDAProb3.cpp
- OscProbCalcer/OscProbCalcer_CUDAProb3.h
- OscProbCalcer/OscProbCalcer_CUDAProb3Linear.cpp
- OscProbCalcer/OscProbCalcer_CUDAProb3Linear.h
- OscProbCalcer/OscProbCalcer_NuFASTLinear.cpp
- OscProbCalcer/OscProbCalcer_NuFASTLinear.h
- OscProbCalcer/OscProbCalcer_Prob3ppLinear.cpp
- OscProbCalcer/OscProbCalcer_Prob3ppLinear.h
- OscProbCalcer/OscProbCalcer_ProbGPULinear.cpp
- OscProbCalcer/OscProbCalcer_ProbGPULinear.h
- Oscillator/OscillatorBase.cpp
- Oscillator/OscillatorBase.h
- Oscillator/OscillatorBinned.cpp
- Oscillator/OscillatorBinned.h
- Oscillator/OscillatorFactory.cpp
- Oscillator/OscillatorFactory.h
- Oscillator/OscillatorUnbinned.cpp
- Oscillator/OscillatorUnbinned.h
- Now all destructors are public which means we can actually delete objects
- Some objects were not deleted most notably temp arrays in ProbGPU :(
- Use override to help indicate that fucntions overrides virtual in base class
- Install in cmake new constants directory
- Safer headers with total path
- Pass vectors by reference instead of copying did short test
before
after
> Desctructor and vectors by reference

- OscProbCalcer/OscProbCalcerBase.cpp
- OscProbCalcer/OscProbCalcer_CUDAProb3Linear.cpp
Fix antineutrino support
Fix the index finding for antineutrinos which are given a negative oscillation channel and similarly, fix the antineutrino support in CUDAProb3Linear which [after Liban's changes] no longer uses the cudaprob3::Antineutrino type to determine whether an event is neutrino or antineutrino
> Fix antineutrino support

- OscProbCalcer/OscProbCalcerBase.cpp
Use stl functions to find energy and cosine zenith indices with binary search rather than brute force search
Use stl functions for binary search
> Perform binary search when finding energy and cosineZ indices - it's now very speedy

- .github/workflows/CIValidations.yml
- Constants/OscillatorConstants.h
- Docs/DockerFiles/Alma9/Dockerfile
Code was awlays using double, we always define UseDouble so this was wrong :(
> Fix double vs float build

- Apps/Analysis.cpp
- Apps/DragRace.cpp
- Apps/OscProbCalcerComparison.cpp
- Apps/SingleOscProbCalcer.cpp
- Apps/SingleOscillator.cpp
- Constants/OscillatorConstants.h
Move repeatedly defined constants and config vectors into the constants structure so they are only defined in one place. Addresses issue https://github.com/dbarrow257/NuOscillator/issues/25
> Move oscillation parameters and configs to the constants structure

- .github/workflows/CIValidations.yml
- CMakeLists.txt
- cmake/Modules/NuOscillatorUtils.cmake
Some minor tweaks to cmake. If user have no clue and just call cmake.. it will prepare NuOsicllator with just NuFast as default
- Now there are default values set. So no longer there is need to loop over to make sure everything is set.
- Get NuHepMC Tools eariler to use cmessage
- Bumped version...
> Default Cmake settings

- OscProbCalcer/OscProbCalcer_CUDAProb3.cpp
- OscProbCalcer/OscProbCalcer_CUDAProb3Linear.cpp
- OscProbCalcer/OscProbCalcer_NuFASTLinear.cpp
- OscProbCalcer/OscProbCalcer_OscProb.cpp
- OscProbCalcer/OscProbCalcer_Prob3ppLinear.cpp
- OscProbCalcer/OscProbCalcer_ProbGPULinear.cpp
Multiplication result may overflow 'int' before it is converted to 'long'. Therafore let's do static cast to long and then proceed to multiplcation
> Avoid potetnial overflow

- OscProbCalcer/OscProbCalcer_OscProb.cpp
- OscProbCalcer/OscProbCalcer_OscProb.h
We can improve the OscProb speed by computing all detected flavours at once using the OscProb::PMNS_Base::ProbMatrix function.
- Using ProbMatrix as probability method
- Made the code a bit more DRY by reusing functions
> perf: Use ProbMatrix to parallelize computations

- CMakeLists.txt
- README.md
I personally rarely define OMP_NUM_THREADS. Then I get blank cmake message (annoing). Expanded cmake in case of not having this variable defined to print all avaialbe threads from `lscpu`.
In addition very short explanation of what NuOscillator is to make project look more professional.
> If omp_num_threads not defined just print all available threads

- OscProbCalcer/OscProbCalcerBase.cpp
- OscProbCalcer/OscProbCalcerBase.h
Issues were being found (https://github.com/dbarrow257/NuOscillator/issues/60) when the probability was exactly equal to 1.0 or slightly above 1.0 due to numerical precision. Now allow a small precision band to set the probabilities to exactly 0.0 or 1.0 if just outside the range. The precision has a default value of 1e-6 but can be overwritable from config
> Feature: Update SanitiseProbabilities function to allow a small precision allowance

- Constants/OscillatorConstants.h
- Oscillator/OscillatorBase.cpp
- Oscillator/OscillatorBase.h
- Oscillator/OscillatorBinned.h
- Oscillator/OscillatorUnbinned.h
- Passing std: contianers by refernce is faster
- There was single memory leak (minor)
- Use override to indicate fucntion overrides virtaul function
> tidy: Pass std containers by refernce and more

- OscProbCalcer/OscProbCalcer_OscProb.cpp
Adds description of OscProb types and propagation method to `fImplementationName`
closes #78
> fix: Add extra labels to implementation name

- .github/workflows/CIBuild.yml
- CMakeLists.txt
- Docs/DockerFiles/Rocky9/Dockerfile
Somone did genius move and hide defions under ifdef
https://github.com/mach3-software/CUDAProb3/blob/35b5dbeaf87451efa6b1953591faf91bb3c46e73/atmoscudapropagator.cuh#L23
Code could compile fine. But when icnlduing it compiler couldn't find becasue defiention wasn't progpagted by cmake.
I fixed this in NuOscillator.
[TimingDistribution.pdf](https://github.com/user-attachments/files/18766673/TimingDistribution.pdf)
> Fix CudaProbLinear

- CMakeLists.txt
I am trying to make MaCh3 usable on Mac and this means NuOscillator should be also usable with Clang.
Based on
https://stackoverflow.com/questions/33357029/using-openmp-with-clang
> Clang OMP support

- OscProbCalcer/OscProbCalcer_CUDAProb3.cpp
- OscProbCalcer/OscProbCalcer_CUDAProb3Linear.cpp
- OscProbCalcer/OscProbCalcer_NuFASTLinear.cpp
- README.md
Implement Mulithreading to NuFast this allowed to  make it at least twice faster.
Before: 0.030 milisecond
4 CPU:  0.020 mILI
8 CPI: 0.016 MILI
This is USING **50 Energy points**. T2K uses ~300 bins.
If we move to Unbinned (1001 Energy points) it scales very well
2 CPU: 0.71 MILI
4 CPU: 0.54 MILI
8 CPU:  0.40 MILI
omp_get_num_threads() returns threads in parraler region while omp_get_max_threads() available threads (max or output of OMP_NUM_THREADS) using later is better as doesn't reuiwer stuipid omp single etc.
> Fast NuFast

- CMakeLists.txt
By Default Prob3++ compiles with O2 optimisation.
If somone defines NuOscillator to use O3 flag then this flag nomrally would not be propagated to Prob3++ :(
This is what this PR changes. NuOsc flags will be propagated to Prob3++
Prob3++
By default:: 0.49
Wiht O3 (Test 1): 0.45
+Fast math and inline ALL (Test 2): 0.41
All plots with compilation and speed can be found below but clearly only adding compilation flags helped speed up Prob3++ :)
Test 1
Test 2
> Prbo3++ Compilation

- OscProbCalcer/OscProbCalcer_CUDAProb3.cpp
Setting the production heights averaging only once instead of calling that at each instance of CalculateProbabilities
> Optimizing heights averaging

- OscProbCalcer/OscProbCalcer_OscProb.cpp
- OscProbCalcer/OscProbCalcer_OscProb.h
Use SIMD to introduce minor speed of around 2-5% to OscProb
Before
after
> feat: Minor OscProb SpeedUp

- cmake/Templates/setup.NuOscillator.sh.in
Trying to edit the setup functions to be portable and sourceable across different unix shells. I tested this version with bash, sh, zsh, ksh, and dash. This script can be sourced from anywhere, independent on your current $(pwd).
Unfortunately, this is cannot be sourced in csh and tcsh shells. Likely a specific script is needed (though I hope nobody's been using csh).
1) Switching to the enhanced bash c++-like syntax ```[[ ]],  ==```, etc., which is available in most modern versions of unix shells (unlike combinations of bash extension with POSIX statements) and making it consistent in the setup scripts.
2) ```function function_name () {}``` is also a mixture of several definition practices interpreted correctly in bash only. The edited way is accessible from all bash, zsh, ksh, and dash …
> feat: Universal setup: bash, sh, zsh, ksh, dash

- CMakeLists.txt
- OscProbCalcer/CMakeLists.txt
- I was having comoilation error on one of clusters so had to add link lib
- Let's use commit for prob3++. I tried contaicting Roger to make a tag but he didn't reply yet [once he makes tag we shal update]
> Fix cmake and use version cotnrol for Prob3++

- CMakeLists.txt
I changed the name of the NuFast repo to NuFast-LBL. For now github will automatically redirect, but cmake should eventually update.
> Update CMakeLists.txt to new NuFast-LBL repo
